name: Android 13 5.10
permissions:
  contents: write  # Allow writing to repository contents (for pushing tags)
  actions: write   # Allows triggering actions
  
on:
  workflow_call:  # This allows this workflow to be called from another workflow
    inputs:
      runner:
        required: true
        type: string
      lto_type:
        required: true
        type: string
      kernelsu_variant:
        required: true
        type: string
      kernelsu_branch:
        required: true
        type: string
      kernelsu_branch_other:
        required: false
        type: string
  
jobs:
  build-kernel-a13-5-10-kernelsu-susfs:
    strategy:
      matrix:
        include:
          - sub_level: "189"
            os_patch_level: "2023-11"
          - sub_level: "198"
            os_patch_level: "2024-01"
          - sub_level: "205"
            os_patch_level: "2024-03"
          - sub_level: "209"
            os_patch_level: "2024-05"
          - sub_level: "210"
            os_patch_level: "2024-06"
          - sub_level: "214"
            os_patch_level: "2024-07"
          - sub_level: "218"
            os_patch_level: "2024-08"
          - sub_level: "223"
            os_patch_level: "2024-11"
          - sub_level: "228"
            os_patch_level: "2025-01"
          - sub_level: "X"
            os_patch_level: "lts"
    uses: ./.github/workflows/gki-kernel.yml
    secrets: inherit
    with:
      android_version: "android13"
      kernel_version: "5.10"
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      runner: ${{ inputs.runner }}
      lto_type: ${{ inputs.lto_type }}
      kernelsu_variant: ${{ inputs.kernelsu_variant }}
      kernelsu_branch: ${{ inputs.kernelsu_branch }}
      kernelsu_branch_other: ${{ inputs.kernelsu_branch_other }}
