name: Build Android 14 6.1 GKI Kernels

on:
  workflow_call:  # This allows this workflow to be called from another workflow
    inputs:
      runner:
        required: true
        type: string
      lto_type:
        required: true
        type: string
      next_branch:
        required: true
        type: string
      next_branch_other:
        required: false
        type: string

jobs:
  build-kernel-a14-6-1-kernelsu-susfs:
    strategy:
      matrix:
        include:
          - sub_level: "25"
            os_patch_level: "2023-10"
          - sub_level: "43"
            os_patch_level: "2023-11"
          - sub_level: "57"
            os_patch_level: "2024-01"
          - sub_level: "68"
            os_patch_level: "2024-03"
          - sub_level: "75"
            os_patch_level: "2024-05"
          - sub_level: "78"
            os_patch_level: "2024-06"
          - sub_level: "84"
            os_patch_level: "2024-07"
          - sub_level: "90"
            os_patch_level: "2024-08"
          - sub_level: "112"
            os_patch_level: "2024-11"
          - sub_level: "115"
            os_patch_level: "2024-12"
          - sub_level: "118"
            os_patch_level: "2025-01"
          - sub_level: "X"
            os_patch_level: "lts"
    uses: ./.github/workflows/gki-kernel.yml
    secrets: inherit
    with:
      android_version: "android14"
      kernel_version: "6.1"
      sub_level: ${{ matrix.sublevel }}
      os_patch_level: ${{ matrix.os_patch_level }}
      runner: ${{ inputs.runner }}
      lto_type: ${{ inputs.lto_type }}
      next_branch: ${{ inputs.next_branch }}
      next_branch_other: ${{ inputs.next_branch_other }}
